######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 31 23:14:43 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += servertester.h
SOURCES += servertester.cpp
QT += xml \
network
